ARCH = x86_64
TARGET = libk.a
SRCS = $(wildcard src/*.c src/**/*.c)
ASM_SRCS = $(wildcard src/*.asm)
OBJS = $(SRCS:.c=.o) $(ASM_SRCS:.asm=.o)

CFLAGS = -ffreestanding -pedantic -Wall -Wextra -Werror --std=c11 -mno-red-zone -mno-mmx -Iinclude -I../shared -I../build/include -D_SMPLOS_LIBK
LINK_OPTS = -ffreestanding -nostdlib -lgcc -z max-page-size=0x1000
AR_OPTS = rcs

CC = $(ARCH)-elf-gcc
LD = $(ARCH)-elf-ld
AR = $(ARCH)-elf-ar
ASM = nasm

.PHONY: clean

%.o : %.c
	$(CC) -c $(CFLAGS) $(CPPFLAGS) $< -o $@

%.o : %.asm
	$(ASM) -felf64 $< -o $@

$(TARGET): $(OBJS)
	$(AR) $(AR_OPTS) $@ $(OBJS)  

all: $(TARGET)

clean:
	rm $(OBJS) || :
	rm $(TARGET) || :

install: 
	cp $(TARGET) ../build

