ARCH = x86_64
TARGET = libc.a
SRCS = $(wildcard src/*.c src/**/*.c)
ASM_SRCS = $(wildcard src/*.asm)
OBJS = $(SRCS:.c=.o) $(ASM_SRCS:.asm=.o)

CFLAGS    = 
LINK_OPTS =
AR_OPTS = rcs

CC = $(ARCH)-elf-gcc
LD = $(ARCH)-elf-ld
AR = $(ARCH)-elf-ar
ASM = nasm

.PHONY: clean

%.o : %.c
	$(CC) -c $(CFLAGS) $(CPPFLAGS) $< -o $@

%.o : %.asm
	$(ASM) -felf64 $< -o $@

$(TARGET): $(OBJS)
	$(AR) $(AR_OPTS) $@ $(OBJS)   

all: $(TARGET)

clean:
    rm $(OBJS) || :
	rm $(TARGET) || :

install: 
	cp $(TARGET) ../build
